### ISSUE TITLE
The latest sphinx-tabs have oversized height with the latest sphinx

### ISSUE THREAD

**Issue by honzajavorek** [djungelorm/sphinx-tabs#38]
<img width="462" alt="Screenshot 2019-04-12 at 09 23 08" src="https://user-images.githubusercontent.com/283441/56019369-af12ad80-5d04-11e9-93e7-a3007eed1a97.png">

-----

It's because the HTML is different now, somehow:

-----

<img width="439" alt="Screenshot 2019-04-12 at 09 24 15" src="https://user-images.githubusercontent.com/283441/56019395-c6ea3180-5d04-11e9-84a1-371966b65897.png">

-----

The `<p>` didn't use to be there. Versions:

```toml
[packages]
sphinx = "~=2.0.1"
sphinx-tabs = "~=1.1.10"

[dev-packages]
sphinx-autobuild = "==0.7.1"
sphinx-rtd-theme = "==0.4.3"
pylama = "~=7.7.1"
```

**Comment by honzajavorek** [comment]
Workaround:

```css
/*
  Workaround for https://github.com/djungelorm/sphinx-tabs/issues/38
*/
.sphinx-tabs .sphinx-menu .item p {
  margin: 0;
}
```
